[package]
name = "visualizer"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.16.0"
rustfft = "6.4.0"
owo-colors = "4.2.2"
windowfunctions = "0.1.1"
terminal_size = "0.4.3"
toml = "0.8"
serde = { version = "1.0.226", features = ["derive"] }
savgol-rs = "0.1.0"